server_port: 9001
service_map_backend: http://api.hel.fi/servicemap/v1
linkedevents_backend: http://api.hel.fi/linkedevents/v0.1
static_path: /
livereload: true
url_prefix: /
# user_location_override: [60.171111, 24.943889]
