server:
    address: 127.0.0.1
    port: 9001
street_address_languages:
    - fi
    - sv
supported_languages:
    - fi
    - sv
    - en
service_map_backend: https://api.hel.fi/servicemap
linkedevents_backend: https://api.hel.fi/linkedevents
respa_backend: https://api.hel.fi/respa
open311_write_backend: https://api.hel.fi/servicemap/open311
open311_backend: https://asiointi.hel.fi/palautews/rest
otp_backend: https://api.digitransit.fi/routing
static_path: /static/
livereload: true
url_prefix: /
# user_location_override: [60.171111, 24.943889]
# sentry_url: http://4e10e9d3f27a440180a5e851a0228754@83.136.249.107/sentry/2
debug_state: false
mobile_ui_breakpoint: 768 # Mobile UI is used below this screen width.
page_size: 1000
enable_statistics: true
use_client_bundle: false
